import { useState } from "react";
import Head from "next/head";
import { useTranslations } from "next-intl";
import { useRouter } from "next/router";

import { Fragment } from "react";
import { Popover, Transition } from "@headlessui/react";
import {
  AnnotationIcon,
  ChatAlt2Icon,
  ChatAltIcon,
  DocumentReportIcon,
  HeartIcon,
  InboxIcon,
  MenuIcon,
  PencilAltIcon,
  QuestionMarkCircleIcon,
  ReplyIcon,
  SparklesIcon,
  TrashIcon,
  UsersIcon,
  XIcon,
} from "@heroicons/react/outline";
import { ChevronDownIcon } from "@heroicons/react/solid";
import Header from "../components/Header";
import Hero from "../components/Hero";
import QuienSoy from "../components/QuienSoy";
import About from "../components/About";

import Process from "../components/Process";
import NewsLetter from "../components/NewsLetter";
import Footer from "../components/Footer";
import Feature from "../components/Feature";

import Register from "../components/Register";

function classNames(...classes) {
  return classes.filter(Boolean).join(" ");
}

export default function Index(props) {
  const [open, setOpen] = useState(false);

  function onRegister() {
    setOpen(true);
  }

  return (
    <div className="bg-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Register open={open} setOpen={setOpen} />
      <main>
        <Header />
        <Hero onRegister={onRegister} />

        <QuienSoy />
        <Process onRegister={onRegister} />
        <Feature />
        <div className="bg-indigo-600">
          <div className="max-w-2xl mx-auto text-center py-16 px-4 sm:py-20 sm:px-6 lg:px-8">
            <h2 className="text-3xl font-extrabold text-white sm:text-4xl">
              <span className="block">Abierto al publico</span>
              <span className="block text-sm ">por tiempo limitado</span>
            </h2>

            <a
              onClick={props.onRegister}
              className="mt-8 w-full inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-indigo-600 bg-white hover:bg-indigo-50 sm:w-auto"
            >
              Registrese gratis con LinkedIn
            </a>
            <p className="mt-4 text-lg leading-6 text-indigo-200">
              Aproveche esta oportunidad HOY, no hay garantia de que este
              mañana.
            </p>
          </div>
        </div>

        <NewsLetter />
      </main>
      <Footer />
    </div>
  );
}

export function getStaticProps({ locale }) {
  return {
    props: {
      messages: {
        ...require(`../messages/${locale}.json`),
      },
    },
  };
}
